### ISSUE TITLE
stereo mode persists even when VR mode is exited (in native WebVR on Chrome for Android)

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#256]
reproduced in Chrome 65 on an Android Pixel 2 device:

0. ensure that the _**WebVR**_ flag is **Enabled** from `chrome://flags#enable-webvr`
1. using Chrome on Android (current release: 65), navigate to the demo scene at https://mozilla.github.io/unity-webvr-export/ (or your `localhost` server)
2. click the VR-icon button to enter VR mode.
3. put your mobile phone in your Daydream headset viewer.
4. move your head around to view the scene in VR mode.
5. take the headset off.
6. press the × icon in the corner to close/exit Daydream's Google VR mode.
7. notice the screen is split in half, still in stereo mode (should be reverted to mono mode).
8. notice, even after subsequent clicks of the VR-icon button, it is impossible to revert to mono mode. (a page refresh obviously does, but nothing else appears to.)

**Comment by caseyyee** [comment]
Also happens with Oculus Go.

**Comment by caseyyee** [comment]
fixed with:
https://github.com/mozilla/unity-webvr-export/commit/d121593fe721a7d3ef52e51c1cc364ea54a172d2

Issue was that on mobile, the `vrdisplaydeactivate` events were not being fired.  In any case, the enter/exit VR logic has been changed up and it's now working properly: https://github.com/mozilla/unity-webvr-export/blob/master/Assets/WebGLTemplates/WebVR/webvr.js#L304-L314
