### ISSUE TITLE
Support for lightweight render pipeline?

### ISSUE THREAD

**Issue by omgitsraven** [mozilla/unity-webvr-export#285]
I'm trying out Unity's new Lightweight Render Pipeline feature: https://blogs.unity3d.com/2018/02/21/the-lightweight-render-pipeline-optimizing-real-time-performance/ and while I have it working in the editor, when I try to build and run it in the browser, all I see is blue? (And it worked fine before converting to the Lightweight Render Pipeline.) Is this not supported with the WebVR Exporter?

**Comment by Banyango** [comment]
Just referencing this issue from the ScriptableRenderPipeline issue tracker here. 

https://github.com/Unity-Technologies/ScriptableRenderPipeline/issues/1238

> Hi Tyler. This issue seems related to the fact WebGL doesn't support the job system (which SRP depends on). We are looking into that. I'll get back to you when I have more information.

**Comment by caseyyee** [comment]
@Banyango As of 2018.2, this seems to be working.  I tried using the Lightweight Render Pipeline as per https://www.youtube.com/watch?v=HgZHwfF5SuM&t=1s and it seemed to work without issue!

Seems like earlier versions might have been a problem since it was not yet fully supported using the WebGL platform.

I'm exploring this option to see if we can improve performance for mobile!
