### ISSUE TITLE
VR state is not retained when moving scene to scene

### ISSUE THREAD

**Issue by MrCreightonD** [mozilla/unity-webvr-export#290]
Created a game with WebVR but vr state reverts back to NORMAL when switching to another scene instead of staying in ENABLED.  I was able to get it to retain the ENABLED state when switching scenes but now it loses its camera rotation and projection upon loading the new scene.

**Comment by cvan** [comment]
cc @caseyyee

**Comment by cflorea1** [comment]
I had the same issue some while back. Fixed it by using only one instance of WebVRCameraSet and preserving it with [Object.DontDestroyOnLoad](https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html). A different approach could be putting the WebVRCameraSet prefab in a start scene and loading any following scenes [additively](https://docs.unity3d.com/ScriptReference/SceneManagement.LoadSceneMode.Additive.html).

**Comment by delapuente** [comment]
I like the preserving the manager across the scenes like @banyango just did in #302 but I would want to disable this feature on demand.

**Comment by cvan** [comment]
can this issue be closed, or is there remaining work to be done after @Banyango's PR #302? thanks, @Banyango, @MrCreightonD, @cflorea1, @delapuente, and @caseyyee!

**Comment by MrCreightonD** [comment]
Yes I believe it can be closed. cflorea1's solution was similar to what I ended up implementing. I actually just copying the player object from scene to scene using a scene manager script.

**Comment by Banyango** [comment]
Hey, yeah this can be closed. The manager is now DoNotDestroyOnLoad by default, and that should persist the vr state across scene changes.

I think there might still be an issue though, if a user opts out of the DoNotDestroyOnLoad and then changes the scene. Which is why I was looking into grabbing the current state of the VR from the JS when the manager is created, but I haven't got that working quite yet. 

I raised issue #309 to cover this case.
