### ISSUE TITLE
move webvr.js into .jslib

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#9]
so that unity can manage the loading of the file.

**Comment by delapuente** [comment]
It is not worth the effort. This is intended to embed more than one game instance per webpage and I would consider that an advanced feature. Furthermore, it increases the complexity of the module since .jslib files are actually EMSCripten modules and we would need to [convert our code to this format](https://www.npmjs.com/package/emscripten-library-generator).

**Comment by caseyyee** [comment]
Also, cannot seem to control script order and such. Closing for now since the current setup is serviceable.
